Sistema_Gestion_Olimpiadas_FULLAPIBackend_ANd_Frontend_MVC/Front/Presentacion/Controllers/EventoController.cs
using DTO;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Presentacion.Models;
using System.Threading;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Presentacion.Controllers
{
    public class EventoController : Controller
    {
        //GET: FiltrosEventos
        public ActionResult FiltrosEventos()
        {
            return View();
        }

        //Get: EventosXId  
        public ActionResult GetEventosXIdDisciplina(int id)
        {
            try
            {
                string url = "http://localhost:5118/api/eventos/disciplina/" + id;
                HttpClient cliente = new HttpClient();
                Task<HttpResponseMessage> tarea1 = cliente.GetAsync(url);
                tarea1.Wait();

                HttpResponseMessage respuesta = tarea1.Result;
                HttpContent body = respuesta.Content;

                Task<string> tarea2 = respuesta.Content.ReadAsStringAsync();
                tarea2.Wait();

                if (respuesta.IsSuccessStatusCode)
                {
                    string json = tarea2.Result;
                    IEnumerable<ListadoEventosDTO> dto = JsonConvert.
                        DeserializeObject<IEnumerable<ListadoEventosDTO>>(json);
                    return View(dto);
                }
                else
                {
                    string error = tarea2.Result;
                    ViewBag.Error = error;
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Ocurrió un error inesperado: " + ex.Message;
            }
            return View(new List<ListadoEventosDTO>());
        }

        //Get: EventosXNombre
        public ActionResult GetEventosXNombre(string nombre)
        {
            try
            {
                string url = "http://localhost:5118/api/eventos/nombre/" + nombre;
                HttpClient cliente = new HttpClient();
                Task<HttpResponseMessage> tarea1 = cliente.GetAsync(url);
                tarea1.Wait();

                HttpResponseMessage respuesta = tarea1.Result;
                HttpContent body = respuesta.Content;

                Task<string> tarea2 = respuesta.Content.ReadAsStringAsync();
                tarea2.Wait();

                if (respuesta.IsSuccessStatusCode)
                {
                    string json = tarea2.Result;
                    IEnumerable<ListadoEventosDTO> dto = JsonConvert.
                        DeserializeObject<IEnumerable<ListadoEventosDTO>>(json);
                    return View(dto);
                }
                else
                {
                    string error = tarea2.Result;
                    ViewBag.Error = error;
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Ocurrió un error inesperado: " + ex.Message;
            }
            return View(new List<ListadoEventosDTO>());
        }

        //Get: EventosXNombre
        public ActionResult GetEventosXRangoFechas(DateTime fechaIni, DateTime fechaFin)
        {
            try
            {
                string url = $"http://localhost:5118/api/eventos/rangoFecha/{fechaIni:yyyy-MM-dd},{fechaFin:yyyy-MM-dd}";
                HttpClient cliente = new HttpClient();
                Task<HttpResponseMessage> tarea1 = cliente.GetAsync(url);
                tarea1.Wait();

                HttpResponseMessage respuesta = tarea1.Result;
                HttpContent body = respuesta.Content;

                Task<string> tarea2 = respuesta.Content.ReadAsStringAsync();
                tarea2.Wait();

                if (respuesta.IsSuccessStatusCode)
                {
                    string json = tarea2.Result;
                    IEnumerable<ListadoEventosDTO> dto = JsonConvert.
                        DeserializeObject<IEnumerable<ListadoEventosDTO>>(json);
                    return View(dto);
                }
                else
                {
                    string error = tarea2.Result;
                    ViewBag.Error = error;
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Ocurrió un error inesperado: " + ex.Message;
            }
            return View(new List<ListadoEventosDTO>());
        }

        //Get: EventosXPuntaje
        public ActionResult GetEventosXRangoPuntajes(decimal ini, decimal max)
        {
            try
            {
                string url = $"http://localhost:5118/api/eventoAtleta/rangoPuntaje/{ini},{max}";
                HttpClient cliente = new HttpClient();
                Task<HttpResponseMessage> tarea1 = cliente.GetAsync(url);
                tarea1.Wait();

                HttpResponseMessage respuesta = tarea1.Result;
                HttpContent body = respuesta.Content;

                Task<string> tarea2 = respuesta.Content.ReadAsStringAsync();
                tarea2.Wait();

                if (respuesta.IsSuccessStatusCode)
                {
                    string json = tarea2.Result;
                    IEnumerable<ListadoEventoAtletaDTO> dto = JsonConvert.
                        DeserializeObject<IEnumerable<ListadoEventoAtletaDTO>>(json);
                    return View(dto);
                }
                else
                {
                    string error = tarea2.Result;
                    ViewBag.Error = error;
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Ocurrió un error inesperado: " + ex.Message;
            }
            return View(new List<ListadoEventoAtletaDTO>());
        }
    }
}

Sistema_Gestion_Olimpiadas_FULLAPIBackend_ANd_Frontend_MVC/Front/Presentacion/Controllers/UsuariosController.cs
using DTO;
using Microsoft.AspNetCore.Mvc;
using Presentacion.Models;

namespace Presentacion.Controllers
{
    public class UsuariosController : Controller
    {
        //public UsuariosController(IAltaUsuario cuAltaUsuarios, IListadoUsuarios cuListadoUsuarios, IListadoRoles cuListadoRoles,
        //    IBajaUsuario cuBajaUsuario, IUpdateUsuario cUUpdateUsuario, ILoginUsuario cULoginUsuario, IBuscarUsuarioPorID cuBuscarUsuarioPorID)
        //{
        //    CUAltaUsuario = cuAltaUsuarios;
        //    CUListadoUsuarios = cuListadoUsuarios;
        //    CUListadoRoles = cuListadoRoles;
        //    CUBajaUsuario = cuBajaUsuario;
        //    CUUpdateUsuario = cUUpdateUsuario;
        //    CULoginUsuario = cULoginUsuario;
        //    CUBuscarUsuarioPorID = cuBuscarUsuarioPorID;
        //}

        //public bool EstaLogueado()
        //{
        //    string email = HttpContext.Session.GetString("emailUsuarioLogueado");
        //    try
        //    {
        //        Usuario userLogueado = CULoginUsuario.FindByMail(email);
        //        if (userLogueado == null)
        //        {
        //            return false;
        //        }
        //        else
        //        {
        //            return true;
        //        }
        //    }
        //    catch (ExcepcionesUsuario ex)
        //    {
        //        ViewBag.Error = ex.Message;
        //        return false;
        //    }
        //}

        //public bool EsAdmin()
        //{
        //    string admin = HttpContext.Session.GetString("rolUsuarioLogueado");
        //    if (admin == "Administrador")
        //    {
        //        return true;
        //    }
        //    else
        //    {
        //        return false;
        //    }
        //}

        //// GET: UsuariosController
        //public ActionResult ListaUsuarios()
        //{
        //    if (EstaLogueado() && EsAdmin())
        //    {
        //        string emailUsuarioLogueado = HttpContext.Session.GetString("emailUsuarioLogueado");
        //        Usuario userLogueado = CULoginUsuario.FindByMail(emailUsuarioLogueado);
        //        ViewBag.Usuario = userLogueado;
        //        IEnumerable<ListadoUsuariosDTO> dtos = CUListadoUsuarios.ObtenerListado();
        //        return View(dtos);
        //    }
        //    else
        //    {
        //        return RedirectToAction("Index", "Home");
        //    }
        //}

        //// GET: UsuariosController/Details/5
        //public ActionResult Details(int id)
        //{
        //    if (EstaLogueado() && EsAdmin())
        //    {
        //        AltaUsuarioDTO user = CUBuscarUsuarioPorID.BuscarUsuarioId(id);
        //        return View(user);
        //    }
        //    else
        //    {
        //        return RedirectToAction("Index", "Home");
        //    }
        //}

        //// GET: UsuariosController/Create
        //public ActionResult Create()
        //{
        //    if (EstaLogueado() && EsAdmin())
        //    {
        //        try
        //        {
        //            AltaUsuarioViewModel vm = new AltaUsuarioViewModel();
        //            vm.DTOAltaUsuario = new AltaUsuarioDTO();
        //            vm.RolesDTO = CUListadoRoles.ObtenerListado();
        //            return View(vm);
        //        }
        //        catch (ExcepcionesUsuario ex)
        //        {
        //            ViewBag.Error = ex.Message;
        //            return RedirectToAction("Index", "Home");
        //        }
        //    }
        //    else
        //    {
        //        return RedirectToAction("Index", "Home");
        //    }

        //}

        //// POST: UsuariosController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(AltaUsuarioViewModel vm)
        //{
        //    try
        //    {
        //        string? emailUsuarioLogueado = HttpContext.Session.GetString("emailUsuarioLogueado");
        //        DateTime fecha = DateTime.Now.Date;
        //        string fechaFormateada = fecha.ToString("dd/MM/yyyy");
        //        string horaFormateada = DateTime.Now.ToString("HH:mm");
        //        vm.DTOAltaUsuario.EmailAdmin = emailUsuarioLogueado;
        //        vm.DTOAltaUsuario.Date = fechaFormateada;
        //        vm.DTOAltaUsuario.Hora = horaFormateada;
        //        CUAltaUsuario.Alta(vm.DTOAltaUsuario);
        //        return RedirectToAction(nameof(ListaUsuarios));
        //    }
        //    catch (ExcepcionesUsuario ex)
        //    {
        //        ViewBag.Error = ex.Message;
        //    }
        //    catch (Exception ex)
        //    {
        //        ViewBag.Error = "No es posible realizar el alta al Usuario";
        //    }
        //    vm.RolesDTO = CUListadoRoles.ObtenerListado();
        //    return View(vm);
        //}

        //// GET: UsuariosController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    if (EstaLogueado() && EsAdmin())
        //    {
        //        AltaUsuarioDTO user = CUBuscarUsuarioPorID.BuscarUsuarioId(id);
        //        AltaUsuarioViewModel vm = new AltaUsuarioViewModel
        //        {
        //            DTOAltaUsuario = user,
        //            RolesDTO = CUListadoRoles.ObtenerListado()
        //        };
        //        return View(vm);
        //    }
        //    else
        //    {
        //        return RedirectToAction("Index", "Home");
        //    }
        //}

        //// POST: UsuariosController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(AltaUsuarioViewModel vm)
        //{
        //    //AltaUsuarioViewModel vmPost = new AltaUsuarioViewModel
        //    //{
        //    //    DTOAltaUsuario = vm.DTOAltaUsuario,
        //    //    RolesDTO = CUListadoRoles.ObtenerListado()
        //    //};
        //    try
        //    {
        //        string? emailUsuarioLogueado = HttpContext.Session.GetString("emailUsuarioLogueado");
        //        DateTime fecha = DateTime.Now.Date;
        //        string fechaFormateada = fecha.ToString("dd/MM/yyyy");
        //        string horaFormateada = DateTime.Now.ToString("HH:mm");
        //        vm.DTOAltaUsuario.EmailAdmin = "Admin-Actualizador " + emailUsuarioLogueado;
        //        vm.DTOAltaUsuario.Date = "Fecha-Actualización " + fechaFormateada;
        //        vm.DTOAltaUsuario.Hora = "Hora-Actualización " + horaFormateada;
        //        CUUpdateUsuario.UpdateUser(vm.DTOAltaUsuario);
        //        return RedirectToAction(nameof(ListaUsuarios));
        //    }
        //    catch (ExcepcionesUsuario ex)
        //    {
        //        ViewBag.Error = ex.Message;
        //    }
        //    return View(vm);
        //}

        //// GET: UsuariosController/Delete/5
        //public ActionResult Delete(string email)
        //{
        //    return View((object)email);
        //}

        //// POST: UsuariosController/DeleteConfirmed
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(string email)
        //{
        //    try
        //    {
        //        CUBajaUsuario.BajaUser(email);
        //        return RedirectToAction("ListaUsuarios", "Usuarios");
        //    }
        //    catch (ExcepcionesUsuario ex)
        //    {
        //        ViewBag.Error = ex.Message;
        //        return View("Delete", "Usuarios");
        //    }
        //    catch (Exception ex)
        //    {
        //        ViewBag.Error = "Ocurrió un error al intentar eliminar al usuario: " + ex.Message;
        //        return View("Delete", "Usuarios");
        //    }
        //}
    }
}

Sistema_Gestion_Olimpiadas_FULLAPIBackend_ANd_Frontend_MVC/Front/Presentacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Olimpiadas 2024</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="" asp-action="">Olimpiadas 2024</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.Session.GetString("rolUsuarioLogueado") == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Login">Inicio de Sesión</a>
                            </li>
                        }
                        else
                        {
                            if (Context.Session.GetString("rolUsuarioLogueado") == "Digitador")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Disciplina" asp-action="Create">Registrar Disciplina</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Disciplina" asp-action="Index">Disciplinas</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Atleta" asp-action="Index">Atletas</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Evento" asp-action="Create">Crear Evento</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Evento" asp-action="Index">Ver Eventos</a>
                                </li>
                                <li class="nav-item ms-auto">
                                    <a class="nav-link text-dark" asp-controller="Home" asp-action="Logout">Salir</a>
                                </li>
                            }
                            else if (Context.Session.GetString("rolUsuarioLogueado") == "Administrador")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Usuarios" asp-action="Create">Registro</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Usuarios" asp-action="ListaUsuarios">Listado Usuarios</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Evento" asp-action="Create">Crear Evento</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Evento" asp-action="Index">Ver Eventos</a>
                                </li>
                                <li class="nav-item ms-auto">
                                    <a class="nav-link text-dark" asp-controller="Home" asp-action="Logout">Salir</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            <p class="text-center">© Obligatorio Olimpiadas. Todos los derechos reservados.</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>